### ISSUE TITLE
Can not add NendSDK

### ISSUE THREAD

**Issue by newstarbka** [fan-ADN/nendSDK-admob-mediation#3]
My gralde show event error log :
Gradle sync failed: Could not find method url() for arguments [http://fan-adn.github.io/nendSDK-Android-lib/library] on repository container.
What I should do to resolve the problem ?

**Comment by ghost** [comment]
Hi, could you take us about more information of issue?

- version of nendSDK
- error log
- build.gradle

And you can check more information about how to use nendSDK-admob-mediation.
https://github.com/fan-ADN/nendSDK-admob-mediation/wiki/Android_en#add-sdk-and-mediation-adapter-to-gradle

Thanks

**Comment by newstarbka** [comment]
Here my gralde code 👍 

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
        maven {
            // nendSDK
            url 'http://fan-adn.github.io/nendSDK-Android-lib/library'
        }
    }
}


dependencies {
    // Other library
 compile 'com.google.android.gms:play-services:+'
    compile 'com.android.support:appcompat-v7:24.0.0'
    compile files('libs/adlantis.jar')
    compile files('libs/adstir.jar')
    compile files('libs/adstirwebview.jar')
    compile files('libs/android-async-http-1.4.4.jar')
    compile files('libs/android-support-v7-recyclerview.jar')
 compile 'com.android.support:multidex:1.0.1'

    // nendメディエーション用アダプター
    compile 'net.nend.android:nend-adapter:1.2.7'
}


My gralde show event error log :
Gradle sync failed: Could not find method url() for arguments [http://fan-adn.github.io/nendSDK-Android-lib/library] on repository container.

**Comment by ghost** [comment]
We tried gradle sync as your build.gradle settings and OK on our build environment.
This issue may caused by own build envrionment.
Please check your build tool version:
- Android Studio
- Gradle

And we recommend to use latest version there tools.
If [This Sample App](https://github.com/fan-ADN/nendSDK-admob-mediation/tree/master/Android/NendMediationTest) also fail to build, you should to check your build environment.

Thanks
